### Crear una nueva Agenda
POST http://localhost:9000/api/agendas
Content-Type: application/json

{
  "id_agenda": 8,
  "fecha": "2025-08-12T10:00:00Z",
  "hora": "12:00",
  "descripcion": "cita ip redireccion",
  "estado": "programada",
  "id_proceso": 1
}

###

### Obtener una Agenda por ID
GET http://localhost:9000/api/agendas/1
Content-Type: application/json

###

### Obtener todas las Agendas
GET http://localhost:9000/api/agendas
Content-Type: application/json

###

### Editar una Agenda
PUT http://localhost:9000/api/agendas/1
Content-Type: application/json

{
  "descripcion": "Reunión importante actualizada",
  "estado": "cancelada"
}

###

### Eliminar una Agenda
DELETE http://localhost:9000/api/agendas/2
Content-Type: application/json


###
