### Crear una nueva Agenda
POST http://localhost:9000/api/agendas
Content-Type: application/json

{
  "id_agenda": 8,
  "fecha": "2025-08-12T10:00:00Z",
  "hora": "12:00",
  "descripcion": "cita ip redireccion",
  "estado": "programada",
  "id_proceso": 1
}

###

### Obtener una Agenda por ID
GET http://localhost:9000/api/agendas/1
Content-Type: application/json

###

### Obtener todas las Agendas
GET http://localhost:9000/api/agendas
Content-Type: application/json

###

### Editar una Agenda
PUT http://localhost:9000/api/agendas/1
Content-Type: application/json

{
  "descripcion": "Reunión importante actualizada",
  "estado": "cancelada"
}

###

### Eliminar una Agenda
DELETE http://localhost:9000/api/agendas/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1lcm9JZGVudGlmaWNhY2lvbiI6Ijk5OTk5OTk5OTkiLCJub21icmUiOiJBbGV4YW5kZXIiLCJhcGVsbGlkbyI6IlBhcnJhIiwiZW1haWwiOiJhbGV4YW5kZXIucGVyZG9tb0BnbWFpbC5jb20iLCJ0ZWxlZm9ubyI6IjAwMDAwMDAwMDAiLCJub21icmVfcm9sIjoiYXNpc3RlbnRlIiwiaWF0IjoxNzQzNjE4Mjg5LCJleHAiOjE3NDM2MjE4ODl9.68115emA353MdyigsdRQrWJrdJrTgLPflNuj93-LS-g


###
