import { StyleSheet } from "react-native";

export const ClientePrincipalScreenStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f8f9fa',
    },
    header: {
      backgroundColor: '#fff',
      padding: 20,
      paddingTop: 50,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
      marginBottom: 10,
    },
    profileContainer: {
      alignSelf: 'center',
      marginBottom: 15,
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 3,
      borderColor: '#4a6da7',
    },
    cameraIcon: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: '#4a6da7',
      borderRadius: 15,
      padding: 5,
    },
    greeting: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#333',
      textAlign: 'center',
      marginBottom: 5,
    },
    subtitle: {
      fontSize: 14,
      color: '#666',
      textAlign: 'center',
      marginBottom: 20,
    },
    menuButton: {
      position: 'absolute',
      top: 50,
      right: 20,
    },
    dropdownMenu: {
      position: 'absolute',
      top: 80,
      right: 20,
      backgroundColor: '#fff',
      borderRadius: 10,
      padding: 10,
      width: 180,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 5,
      zIndex: 100,
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    menuText: {
      marginLeft: 10,
      fontSize: 16,
      color: '#555',
    },
    content: {
      padding: 20,
      paddingBottom: 40,
    },
    cardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    summaryCard: {
      backgroundColor: '#fff',
    //   width: width * 0.43,
      borderRadius: 15,
      padding: 20,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    cardNumber: {
      fontSize: 32,
      fontWeight: 'bold',
      color: '#4a6da7',
      marginBottom: 5,
    },
    cardTitle: {
      fontSize: 14,
      color: '#666',
      textAlign: 'center',
    },
    section: {
      marginBottom: 25,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 15,
      paddingLeft: 5,
    },
    processCard: {
      backgroundColor: '#fff',
      borderRadius: 15,
      padding: 20,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    emptyText: {
      color: '#888',
      marginBottom: 15,
      textAlign: 'center',
    },
    primaryButton: {
      backgroundColor: '#4a6da7',
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 25,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    buttonText: {
      color: '#fff',
      fontWeight: 'bold',
      marginRight: 8,
    },
    fileTypes: {
      fontSize: 12,
      color: '#888',
    },
    statsContainer: {
      backgroundColor: '#fff',
      borderRadius: 15,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    statItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
    },
    statLabel: {
      fontSize: 16,
      color: '#555',
    },
    statValue: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#4a6da7',
    },
    infoCard: {
      backgroundColor: '#fff',
      borderRadius: 15,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    infoTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#4a6da7',
      marginBottom: 10,
    },
    infoText: {
      fontSize: 14,
      color: '#555',
      lineHeight: 20,
    },
    footerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 30,
      height: 100, // Altura fija para el footer
    },
    footerImageLeft: {
      width: '49.5%', // Dejamos un pequeño espacio entre ellas
      height: '100%',
      borderTopLeftRadius: 15,
      borderBottomLeftRadius: 15,
      overflow: 'hidden', // Esto asegura que los bordes se apliquen correctamente
    },
    footerImageRight: {
      width: '49.5%',
      height: '100%',
      borderTopRightRadius: 15,
      borderBottomRightRadius: 15,
      overflow: 'hidden',
    },
  //   footer: {
  //     alignItems: 'center',
  //     marginTop: 30,
  //   },
    logo: {
      width: 150,
      height: 60,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: '#fff',
      borderRadius: 15,
      padding: 25,
    //   width: width * 0.85,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#4a6da7',
      marginBottom: 15,
      textAlign: 'center',
    },
    modalText: {
      fontSize: 16,
      color: '#555',
      lineHeight: 22,
      marginBottom: 20,
    },
    closeButton: {
      backgroundColor: '#4a6da7',
      borderRadius: 8,
      padding: 12,
      alignItems: 'center',
    },
    closeButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
  });